query SELLER_INVOICES($sellerInvoiceParams: SellerInvoiceParams) {
  sellerInvoices(sellerInvoiceParams: $sellerInvoiceParams) {
    id
    status
    invoiceCreatedDate
    totalizers {
      subtotal
      fee
      total
    }
  }
}
