query SELLER_ORDERS($searchOrdersParams: SearchOrdersInput) {
  orders: sellerOrders(searchOrdersParams: $searchOrdersParams) {
    data {
      orderId
      sellerOrderId
      marketplaceOrderId
      totalComission
      totalOrderValue
      status
      statusDescription
      creationDate
      rate {
        itemId
        nameItem
        rate {
          productCommissionPercentage
          freightCommissionPercentage
        }
      }
    }
    paging {
      total
      pages
      currentPage
      perPage
    }
  }
}
